export default {
  login: "sushant61",
  id: 54038425,
  node_id: "MDQ6VXNlcjU0MDM4NDI1",
  avatar_url: "https://avatars.githubusercontent.com/u/54038425?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/sushant61",
  html_url: "https://github.com/sushant61",
  followers_url: "https://api.github.com/users/sushant61/followers",
  following_url:
    "https://api.github.com/users/sushant61/following{/other_user}",
  gists_url: "https://api.github.com/users/sushant61/gists{/gist_id}",
  starred_url: "https://api.github.com/users/sushant61/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/sushant61/subscriptions",
  organizations_url: "https://api.github.com/users/sushant61/orgs",
  repos_url: "https://api.github.com/users/sushant61/repos",
  events_url: "https://api.github.com/users/sushant61/events{/privacy}",
  received_events_url: "https://api.github.com/users/sushant61/received_events",
  type: "User",
  site_admin: false,
  name: null,
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 27,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2019-08-12T17:33:48Z",
  updated_at: "2023-02-14T05:35:59Z",
};
